// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationStoreDAL.EF;

namespace WebApplicationStoreDAL.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20210117175811_AddProducts")]
    partial class AddProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WebApplicationStoreDAL.Entities.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Catalogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mobile phone"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Notebook"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Camera"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Headphones"
                        });
                });

            modelBuilder.Entity("WebApplicationStoreDAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CatalogID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatalogID = 1,
                            Name = "Xiaomi Redmi Note 8"
                        },
                        new
                        {
                            Id = 2,
                            CatalogID = 1,
                            Name = "Xiaomi Redmi Note 9 Pro"
                        },
                        new
                        {
                            Id = 3,
                            CatalogID = 1,
                            Name = "Xiaomi Redmi 7"
                        },
                        new
                        {
                            Id = 4,
                            CatalogID = 1,
                            Name = "Xiaomi Redmi 8"
                        },
                        new
                        {
                            Id = 5,
                            CatalogID = 1,
                            Name = "Xiaomi Mi Note 10 Lite"
                        },
                        new
                        {
                            Id = 6,
                            CatalogID = 1,
                            Name = "Xiaomi Redmi 9C"
                        },
                        new
                        {
                            Id = 7,
                            CatalogID = 2,
                            Name = "Xiaomi RedmiBook 16 JYU4277CN"
                        },
                        new
                        {
                            Id = 8,
                            CatalogID = 2,
                            Name = "Xiaomi Mi Gaming Laptop Enhanced Edition 2019 JYU4144CN"
                        },
                        new
                        {
                            Id = 9,
                            CatalogID = 2,
                            Name = "Xiaomi Mi Notebook Pro 2020 JYU4222CN"
                        },
                        new
                        {
                            Id = 10,
                            CatalogID = 2,
                            Name = "Xiaomi RedmiBook 13 Ryzen Edition 2020 JYU4251CN"
                        },
                        new
                        {
                            Id = 11,
                            CatalogID = 2,
                            Name = "Xiaomi Mi Notebook Air 13.3 JYU4052CN"
                        },
                        new
                        {
                            Id = 12,
                            CatalogID = 2,
                            Name = "Xiaomi Redmi G JYU4313CN"
                        },
                        new
                        {
                            Id = 13,
                            CatalogID = 3,
                            Name = "Xiaomi MiJia 360° Sphere Panoramic Camera"
                        },
                        new
                        {
                            Id = 14,
                            CatalogID = 3,
                            Name = "Xiaomi Mi Home Security Camera 1080p Magnetic Mount"
                        },
                        new
                        {
                            Id = 15,
                            CatalogID = 3,
                            Name = "Xiaomi MiJia 360°"
                        },
                        new
                        {
                            Id = 16,
                            CatalogID = 3,
                            Name = "Xiaomi Mi Home Security Camera Basic"
                        },
                        new
                        {
                            Id = 17,
                            CatalogID = 3,
                            Name = "Xiaomi Dafang PTZ 1080p"
                        },
                        new
                        {
                            Id = 18,
                            CatalogID = 3,
                            Name = "Xiaomi XiaoFang 1080p"
                        },
                        new
                        {
                            Id = 19,
                            CatalogID = 4,
                            Name = "Xiaomi Mi True Wireless Earbuds Basic 2 TWSEJ061LS°"
                        },
                        new
                        {
                            Id = 20,
                            CatalogID = 4,
                            Name = "Xiaomi Mi True Wireless Earphones Lite TWSEJ03WM"
                        },
                        new
                        {
                            Id = 21,
                            CatalogID = 4,
                            Name = "Xiaomi Mi True Wireless Earphones 2 TWSEJ06WM"
                        },
                        new
                        {
                            Id = 22,
                            CatalogID = 4,
                            Name = "Xiaomi Mi In-Ear Pro HD"
                        },
                        new
                        {
                            Id = 23,
                            CatalogID = 4,
                            Name = "Xiaomi Dual Driver Earphones (черный)"
                        },
                        new
                        {
                            Id = 24,
                            CatalogID = 4,
                            Name = "Xiaomi Mi Sports Bluetooth Earphones YDLYEJ01LM (белый)"
                        },
                        new
                        {
                            Id = 25,
                            CatalogID = 4,
                            Name = "Xiaomi Mi Bluetooth TDLYEJ01JY"
                        });
                });

            modelBuilder.Entity("WebApplicationStoreDAL.Entities.Product", b =>
                {
                    b.HasOne("WebApplicationStoreDAL.Entities.Catalog", "Catalog")
                        .WithMany("Products")
                        .HasForeignKey("CatalogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("WebApplicationStoreDAL.Entities.Catalog", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
